task 3
CS342/2024-Prisma pull request #6
Opened 2024-01-17 01:37 UTC by dhruvna1k

# task 3 assignment 1

## :recycle: Current situation & Problem
removed notif permissions and added healthkit data collection

## :books: Documentation
*Please ensure that you properly document any additions in conformance to [Spezi Documentation Guide](https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md).*
yes

## :white_check_mark: Testing

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [ ] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

2024-01-18 07:35 UTC, PSchmiedmayer requested changes
Hi @dhruvna1k,

Thank you for the PR and the improvements. It's a good first version that needs some more work to be merged.

First: Please update your GitHub profile to show your full name and a profile picture!

The PR in its current state is a bit incomplete: It does not update the text in the HealthKit onboarding flow to change the text to the needs of your application. Please complete this before re-requesting a review.

I have noticed that your SwiftLint checks are failing due to some changes in the code that do not conform to the SwiftLint style guide. Please be sure to address them. You can learn more about each rule, including passing and failing examples, in the [Swift Documentation](https://realm.github.io/SwiftLint/rule-directory.html).

In addition, your PR description does not follow the PR template that we introduced in the class, and that is provided by default: https://github.com/CS342/.github/blob/main/.github/pull_request_template.md.
Please follow the following template in your PR description and add a good description of your PR by editing the PR description on the PR page.
Please also add a more descriptive and clear title focusing on the added functionality rather than the assignment task.

Please also read through the ["Keeping your pull request in sync with the base branch"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) documentation to ensure that your branch is up to date with the main branch before you merge it into the main branch.

Please re-request a review once you have implemented all the requested changes.

2024-01-18 07:35 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> +
There is a `healthKit` section below that already contains the configuration for one HealthKit type. Please be sure that you add your additions to the section below (that is added to the main configuration in line 65-67:
```
            if HKHealthStore.isHealthDataAvailable() {
                healthKit
            }
```

2024-01-18 07:35 UTC, PSchmiedmayer commented on Behavior/Onboarding/OnboardingFlow.swift
> +            */
Please do not just comment out code; please remove it if it is no longer needed. You can always go back in the git history and retrieve it if needed.

2024-01-18 07:35 UTC, PSchmiedmayer commented on Behavior/Onboarding/OnboardingFlow.swift
If you and your team determined that your application doesn't need notifications, I would suggest also adapt the logic in this view:
You can also remove the `localNotificationAuthorization` as well as the `.task` modifier if you remove the notification screen. 

Please also remove the file that contains the view so it is removed from the Xcode project as it is no longer displayed. Please also remove the related Strings in the Localizable file. If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.
This will also be very important for the description changes in the onboarding flow.

2024-01-23 00:16 UTC, PSchmiedmayer requested changes
Hi @dhruvna1k,

Thank you for the improvements in the PR!

Thank you for adding the profile picture: Please also update your GitHub profile to show your full name.

Please also read through the ["Keeping your pull request in sync with the base branch"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) documentation to ensure that your branch is up to date with the main branch before you merge it into the main branch.

Please re-request a review once you have implemented all the requested changes.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> +                }
Please either move this section down to the existing healthKit computed property to ensure that you don't need to add the swiftlint disable command. The current `healthKit` computed property is not used.
```suggestion
                healthKit
```

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> +        // swiftlint:disable closure_body_length
Please remove the SwiftLint disable command here and use the existing computed property below.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> -
There is no need to remove this line.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/Resources/Localizable.xcstrings
> +      "extractionState" : "stale",
Please remove all stale localization values.

If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/Resources/Localizable.xcstrings
> +      "extractionState" : "stale",
Please remove all stale localization values.

If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/Resources/Localizable.xcstrings
> +      "extractionState" : "stale",
Please remove all stale localization values.

If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/Resources/Localizable.xcstrings
> +      "extractionState" : "stale",
Please remove all stale localization values.

If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.

2024-01-23 00:16 UTC, PSchmiedmayer commented on Behavior/Resources/Localizable.xcstrings
> +      "comment" : "MARK: Welcome to the Behavior Application!",
Was it your intention to edit the comment in Xcode? I think you might wanted to edit the value of the localization string?

If you want to learn more about localization, please check out this video for more details: https://developer.apple.com/wwdc23/10155.

2024-01-23 08:55 UTC, PSchmiedmayer requested changes
@dhruvna1k We are getting closer to a finished PR.

Please be sure that you run and test the application in Xcode and that you resolve all the conversations completely by addressing them in the code before re-requesting a review.

Once the last conversations are resolved please re-request a review 👍

2024-01-23 08:55 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> +                }
Please be sure that you remove the elements here and only inject the computed property as shown in the comment above. You can even easily commit the suggests with the buttons below the code suggestion.

2024-01-23 08:55 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> +        // swiftlint:disable closure_body_length
Please only resolve conversations once you have actually addressed them.

2024-01-23 08:55 UTC, PSchmiedmayer commented on Behavior/BehaviorDelegate.swift
> -
Please only resolve conversations once you have actually addressed them.

2024-01-23 19:10 UTC, dhruvna1k commented
> @dhruvna1k We are getting closer to a finished PR.
> 
> Please be sure that you run and test the application in Xcode and that you resolve all the conversations completely by addressing them in the code before re-requesting a review.
> 
> Once the last conversations are resolved please re-request a review 👍

Thanks for the reminder. I think I forgot to build the project before commiting/pushing the changes last time. Have made the proper changes and remembered to build this time before committing/pushing. Let me know if this doesn't work.

2024-01-23 19:57 UTC, PSchmiedmayer approved these changes
@dhruvna1k Thank you for the improvements and fixing the last issues! The PR looks great to me and good job with improving it step by step.

We hope you learned some new stills in the PR and are looking forward to a great project this quarter!

2024-01-23 20:09 UTC, merged