Tailor onboarding
CS342/2024-Prisma pull request #8
Opened 2024-01-18 02:03 UTC by evelyn-hur

# *Tailored Onboarding*

## :recycle: Current situation & Problem
- Needed to update text and icons (images) on onboarding flow 

## :gear: Release Notes 
- Edited text on Welcome and Interesting Modules page specific to the LLM-based conversational agent project
- Changed image icons on Welcome page specific to the project

## :white_check_mark: Testing
- Human testing using simulator

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

2024-01-18 17:59 UTC, philippzagar requested changes
Hi @evelyn-hur ,

Thank you for the PR and the improvements. It's a great first version that only needs some more very minor changes! 

Thank you for using the PR template! Please also add a more descriptive and clear title focusing on the added functionality rather than the assignment task. Also, fill out the `Documentation` part of the PR template, it's completely fine to state that you didn't do anything in that aspect within your PR.

Please also read through the ["Keeping your pull request in sync with the base branch"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/keeping-your-pull-request-in-sync-with-the-base-branch) documentation to ensure that your branch is up to date with the main branch before you merge it into the main branch.

Please re-request a review once you updated the branch to the main branch, you have updated the PR description, and addressed some of the in-line comments and I am happy to approve the PR to get it merged 🚀

2024-01-18 17:59 UTC, philippzagar commented on Behavior/Resources/Localizable.xcstrings
> +            "value" : "Baseline surveys, health-related questions, and summary of relevant information"
Great to see that you are using the String Catalog! 🚀

2024-01-18 17:59 UTC, philippzagar commented on Behavior/Onboarding/InterestingModules.swift
> +//                SequentialOnboardingView.Content(
Please remove unnecessary code if not needed. Otherwise, feel free to add more content to the onboarding view!

2024-01-18 17:59 UTC, philippzagar commented on Behavior/Onboarding/Welcome.swift
> +                        Image(systemName: "person.crop.circle")
Nice usage of SF symbols!

2024-01-18 19:10 UTC, philippzagar commented
@evelyn-hur Please add your name and a proper Profile pic to your GitHub profile

2024-01-18 22:52 UTC, evelyn-hur commented
Hi, thank you for your feedback! I made all changes mentioned for your review.

2024-01-22 02:19 UTC, philippzagar approved these changes
Thanks for incorporating the change requests @evelyn-hur! 🚀 
PR is ready to merge!

2024-01-23 21:48 UTC, merged